server:
  port: 8080
  servlet:
    context-path: /app
spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB




  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Marvel
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect






